behaviors:
  Firetrench Agent:
    trainer_type: ppo
    summary_freq: 100
    time_horizon: 4
    hyperparameters:
      batch_size: 64
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.05
        gamma: 0.88
    max_steps: 5e5
    threaded: false
