behaviors:
  Firetrench Agent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2 # there are buffer_size / batch_size = batches per epoch.
      buffer_size: 10 # How many steps to fill the buffer in order to learn
      num_epoch: 3 # meaning the model is trained num_epoch times on the entire buffer during one update cycle.
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.05
        gamma: 0.88
    max_steps: 5e5
    threaded: true
    summary_freq: 5
    time_horizon: 64 # specifies the maximum number of steps to collect in an agent's experience buffer before using these experiences for training
    checkpoint_interval: 100
