behaviors:
  Firetrench Agent:

    trainer_type: ppo
    max_steps: 5e5
    threaded: true
    summary_freq: 254
    time_horizon: 128 # Number of time steps to collect data from the environment before performing an update to the neural network.
    checkpoint_interval: 1000
    keep_checkpoints: 5

    hyperparameters:
      batch_size: 512 #  Number of experiences sampled from the replay buffer for each update step of the neural network.
      buffer_size: 2048 # Maximum number of experiences stored in the replay buffer at any given time.
      num_epoch: 3 # meaning the model is trained num_epoch times on the entire buffer during one update cycle.
      learning_rate: 0.00003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      learning_rate_schedule: linear

    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.05
        gamma: 0.88
